import "./modules/menu";
import "./modules/front/index";
import "./modules/blog";
import "./modules/about";
import "./modules/quick-access";
import "./modules/contact";
import "./modules/single-blog";
import "./modules/course-overview";
import "./modules/date-picker";
