import "./front-page/index";
import "./course/index";
import "./blogs-overview";
import "./contact";
import "./single-blog";
import "./coach-overview";
import "./404-contact-animation";
import "./video-overview";
import "./about-popup-images";
